// Code generated by "stringer -type=mainContent"; DO NOT EDIT.

package tui

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[testCasesMain-0]
	_ = x[cosmosMessagesMain-1]
	_ = x[txDetailMain-2]
	_ = x[errorModalMain-3]
}

const _mainContent_name = "testCasesMaincosmosMessagesMaintxDetailMainerrorModalMain"

var _mainContent_index = [...]uint8{0, 13, 31, 43, 57}

func (i mainContent) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_mainContent_index)-1 {
		return "mainContent(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _mainContent_name[_mainContent_index[idx]:_mainContent_index[idx+1]]
}
